name: dev-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make compile
  contract-test:
    if: ${{ success() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "contract-testing"
  sonarcloud-test:
    if: ${{ success() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "sonarcloud"
  terraform:
    if: ${{ success() }}
    needs: [contract-test,sonarcloud-test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "terraform"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy"
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "smoke-test"