name: dev-github-actions
on: [push]
jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: make compile
  contract-testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "contract-testing"
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - run: echo "sonarcloud"