name: prod
on:
  push:
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo "artifact"
  terraform:
    if: ${{ success() }}
    needs: [artifact]
    runs-on: ubuntu-latest
    steps:
      - run: echo "terraform"
  deploy:
    if: ${{ success() }}
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy"
  smoke-test:
    if: ${{ success() }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "smoke-test"