name: stage
on:
  workflow_dispatch:

jobs:
  pull-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pull artifact"
  terraform:
    if: ${{ success() }}
    needs: [pull-artifact]
    runs-on: ubuntu-latest
    steps:
      - run: echo "terraform"
  deploy:
    if: ${{ success() }}
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy"
  smoke-test:
    if: ${{ success() }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "smoke-test"