name: stage-github-actions
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make compile
      - run: echo "build docker image"
      - run: echo "push docker image"
  contract-test:
    if: ${{ success() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "contract-testing"
  sonarcloud-test:
    if: ${{ success() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "sonarcloud"
  terraform:
    if: ${{ success() }}
    needs: [contract-test,sonarcloud-test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "terraform"
  deploy:
    if: ${{ success() }}
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy"
  smoke-test:
    if: ${{ success() }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "smoke-test"